version: "3.7"

services:
  spotify-client:
    build: .
    ports:
      - 4200:4200
      - 9876:9876
    working_dir:  /home/node/spotify-client
    volumes:
      - ./:/home/node/spotify-client
      - node_modules:/home/node/spotify-client/node_modules

volumes:
  node_modules:
